// =============================================
// 魔法スキル（MP消費）
// 敵・味方共有
// =============================================
const MAGICS = {
  
  fire: {
    name: "火炎",
    type: "magical",
    power: 11,
    cost: 3,
    costType: "mp",
    element: "fire",
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 1,
    effectKey: "fire_ball",
    effectMode: "single",
    description: "敵単体に火の球を放つ。チャ◯カマンよりは強い",
    battleLog: null,
  },
  static: {
    name: "静電気",
    type: "magical",
    power: 0,
    cost: 2,
    costType: "mp",
    element: "electro",
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 2,
    effectKey: "static",
    effectMode: "single",
    description: "敵単体に摩擦で負の電荷を強奪し、指先に滞留したエネルギーが、接触の刹那に火花となり元の器へ還流する一撃",
    battleLog: null,
  },
  heal: {
    name: "ヒール",
    type: "heal",
    power: 15,
    cost: 2,
    costType: "mp",
    element: null,
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 8,
    effectKey: "heal",
    effectMode: "single",
    description: "味方単体にキズパワーパッドよりも万能な回復(HP20〜)",
    battleLog: null,
  },
  blaze: {
    name: "焼炎",
    type: "magical",
    power: 20,
    cost: 10,
    costType: "mp",
    element: "fire",
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 12,
    effectKey: "fire_burst",
    effectMode: "single",
    description: "敵単体にガスバーナーよりは強い炎を放つ",
    battleLog: null,
  },
  high_heal: {
    name: "ハイヒール（靴じゃないよ）",
    type: "heal",
    power: 25,
    cost: 15,
    costType: "mp",
    element: null,
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 15,
    effectKey: "heal",
    effectMode: "single",
    description: "味方単体に総合病院で手術を受ける程度の回復(HP60〜)",
    battleLog: null,
  },
  magic_blaze: {
    name: "魔焔",
    type: "magical",
    power: 25,
    cost: 14,
    costType: "mp",
    element: "fire",
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 18,
    effectKey: "fire_burst",
    effectMode: "single",
    description: "敵グループに中程度の焔魔術",
    battleLog: null,
  },
  explosion: {
    name: "爆焔",
    type: "magical",
    power: 20,
    cost: 18,
    costType: "mp",
    element: "fire",
    target: "all",
    effect: null,
    learnType: "level",
    learnLevel: 21,
    effectKey: "fire_ring",
    effectMode: "all_each",
    description: "敵全体に爆発を伴うダメージ",
    battleLog: null,
  },
  micro_current: {
    name: "微電流",
    type: "magical",
    power: 4,
    cost: 3,
    costType: "mp",
    element: "electro",
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 30,
    effectKey: "micro",
    effectMode: "single",
    description: "電池の代わりになりそうだ",
    battleLog: "/小型モーターが動きそうなくらいの電流が流れた！",
  },
  thunder: {
    name: "電撃",
    type: "magical",
    power: 15,
    cost: 5,
    costType: "mp",
    element: "electro",
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 37,
    effectKey: "electro",
    effectMode: "single",
    description: "敵単体に小規模な電気ダメージ",
    battleLog: null,
  },
  leakage: {
    name: "漏電",
    type: "magical",
    power: 13,
    cost: 7,
    costType: "mp",
    element: "electro",
    target: "all",
    effect: null,
    learnType: "level",
    learnLevel: 40,
    effectKey: "electro",
    effectMode: "all_each",
    description: "敵グループに小規模な電気ダメージ",
    battleLog: "なんと！コンセントにホコリが溜まっていたようだ！漏電している！",
    statusEffect: [{ type: "burn", chance: 0.3 }, { type: "shock", chance: 0.3 }],
  },
  summon_thunder: {
    name: "召雷",
    type: "magical",
    power: 50,
    cost: 30,
    costType: "mp",
    element: "electro",
    target: "all",
    effect: null,
    learnType: "level",
    learnLevel: 50,
    effectKey: "summon_ring",
    effectMode: "all_each",
    description: "敵単体に雷を呼び寄せる",
    battleLog: null,
    statusEffect: { type: "shock", chance: 0.4 },
  },
  hell_fire: {
    name: "獄焔",
    type: "magical",
    power: 60,
    cost: 35,
    costType: "mp",
    element: "fire",
    target: "all",
    effect: null,
    learnType: "level",
    learnLevel: 60,
    effectKey: "hell_fire",
    effectMode: "all_cover",
    description: "敵グループに燃え盛る炎ダメージ",
    battleLog: null,
    statusEffect: { type: "burn", chance: 0.3 },
  },
  thunder_storm: {
    name: "雷嵐",
    type: "magical",
    power: 70,
    cost: 40,
    costType: "mp",
    element: "electro",
    target: "all_random",
    effect: null,
    learnType: "level",
    learnLevel: 73,
    effectKey: "lightning",
    effectMode: "all_each",
    description: "嵐を呼び寄せ、雷が轟く",
    battleLog: "/雷の嵐が起き轟いている...!",
    statusEffect: { type: "shock", chance: 0.3 },
    hits: 7, 
  },
  inferno: {
    name: "地獄焔華",
    type: "magical",
    power: 90,
    cost: 50,
    costType: "mp",
    element: "fire",
    target: "all",
    effect: null,
    learnType: "level",
    learnLevel: 80,
    effectKey: "dark_rose",
    effectMode: "all_cover",
    description: "敵全体に地獄のような炎を浴びせる",
    battleLog: "/辺りは火の海に包まれた！",
    statusEffect: { type: "burn", chance: 1.0 },
  },
};

// =============================================
// 特技1（TP消費）
// 敵・味方共有。敵専用スキルもここに入れる
// =============================================
const SKILLS1 = {
  
  // --- 敵専用 ---
  tackle: {
    name: "体当たり",
    type: "physical",
    power: 2,
    cost: 0,
    costType: null,
    element: null,
    target: "single",
    effect: null,
    description: null,
    battleLog: null,
  },
  wave_attack: {
    name: "波動攻撃",
    type: "physical",
    power: 3,
    cost: 0,
    costType: null,
    element: null,
    target: "all",
    effect: null,
    description: null,
    battleLog: null,
  },
  
  // --- 河野友真 ---
  kiai: {
    name: "気合いだめ",
    type: "buff",
    effectKey: "light",
    effectMode: "single",
    power: 0,
    cost: 20,
    costType: "tp",
    element: null,
    target: "self",
    effect: null,
    learnType: "level",
    learnLevel: 1,
    description: null,
    battleLog: null,
  },
  training_body: {
    name: "筋トレ（自重）",
    type: "buff",
    effectKey: "dust",
    effectMode: "single",
    power: 0,
    cost: 5,
    costType: "tp",
    element: null,
    target: "self",
    effect: { stat: "attack", amount: 1.2, turns: 3 },
    learnType: "level",
    learnLevel: 3,
    description: "自重トレーニングにより、程よくパンプアップする",
    battleLog: "selfは程よくパンプアップした！",
  },
  choke: {
    name: "絞め殺す",
    type: "physical",
    power: 20,
    cost: 10,
    costType: "tp",
    element: null,
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 5,
    effectKey: "fang",
    effectMode: "single",
    description: "敵単体に確率でボス以外の敵を拘束し絞め殺す",
    battleLog: "selfはenemyを絞め殺した！",
    instantDeath: { chance: 1.0, bossImmune: true },
  },
  training_barbell: {
    name: "筋トレ（バーベル）",
    type: "buff",
    effectKey: "rock",
    effectMode: "single",
    power: 0,
    cost: 10,
    costType: "tp",
    element: null,
    target: "self",
    effect: { stat: "attack", amount: 1.3, turns: 3 },
    learnType: "level",
    learnLevel: 15,
    description: "バーベルを使ったトレーニングにより、かなりパンプアップする",
    battleLog: "selfはかなりパンプアップした！",
  },
  seiken: {
    name: "正拳突き",
    type: "physical",
    power: 7,
    cost: 0,
    costType: "tp",
    element: null,
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 1,
    effectKey: "slash3",
    effectMode: "single",
    description: "敵単体に魂を込めた突き",
    battleLog: null,
  },
  fang_rush: {
    name: "牙乱拳",
    type: "physical",
    power: 15,
    cost: 5,
    costType: "tp",
    element: null,
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 10,
    effectKey: "claw",
    effectMode: "single",
    description: "敵グループに5連続の拳",
    battleLog: null,
    hits: 5,
  },
  roundhouse: {
    name: "回し蹴り",
    type: "physical",
    power: 15,
    cost: 5,
    costType: "tp",
    element: null,
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 12,
    effectKey: "slash2",
    effectMode: "single",
    description: "敵単体に回し蹴り",
    battleLog: null,
  },
  training_thumb: {
    name: "筋トレ（親指逆立ち）",
    type: "buff",
    effectKey: "dust",
    effectMode: "single",
    power: 0,
    cost: 20,
    costType: "tp",
    element: null,
    target: "self",
    effect: { stat: "attack", amount: 1.5, turns: 3 },
    learnType: "level",
    learnLevel: 50,
    description: "親指で逆立ちをすることにより、限界ギリギリまでパンプアップをする",
    battleLog: "selfは限界までパンプアップした！",
  },
  training_pinky: {
    name: "筋トレ（小指立て伏せ）",
    type: "buff",
    effectKey: "rock",
    effectMode: "single",
    power: 0,
    cost: 50,
    costType: "tp",
    element: null,
    target: "self",
    effect: { stat: "attack", amount: 2.0, turns: 3 },
    learnType: "level",
    learnLevel: 60,
    description: "小指で全体重を支えることにより、限界を超え、肉体を改造する",
    battleLog: "selfの筋肉量が限界を突破した！",
  },
  static_burst: {
    name: "下敷き静電気バースト",
    type: "physical",
    power: 0,
    cost: 30,
    costType: "tp",
    element: "electro",
    target: "all",
    effect: null,
    learnType: "level",
    learnLevel: 65,
    effectKey: "static",
    effectMode: "all_each",
    description: "下敷きを頭に乗せ、高速で擦ることにより、静電気を起こす。",
    battleLog: "なんと！selfは髪の毛が下敷きに張り付いた！！",
  },
  hand_blade: {
  name: "手刀",
  type: "physical",
  power: 8,
  cost: 0,
  costType: "tp",
  element: null,
  target: "single",
  effect: null,
  learnType: "level",
  learnLevel: 20,
  effectKey: "slash2",
  effectMode: "single",
  critBonus: 0.15,
  description: "敵単体の急所を狙った手刀。クリティカル率が高い",
  battleLog: "切断する勢いで手刀を敵に打ち込んだ！",
},
};

// =============================================
// 特技2（MP消費）
// =============================================
const SKILLS2 = {
  
  blessing_rain: {
    name: "祝福の雨",
    type: "heal",
    power: 15,
    cost: 12,
    costType: "mp",
    element: null,
    target: "all_party",
    effect: null,
    learnType: "level",
    learnLevel: 17,
    effectKey: "cherry",
    effectMode: "all_each",
    description: "5ターンの間、仲間全員に絆創膏より強い回復",
    battleLog: "/優しい雨が降っている...",
  },
  blessing_downpour: {
    name: "祝福の豪雨",
    type: "heal",
    power: 25,
    cost: 30,
    costType: "mp",
    element: null,
    target: "all_party",
    effect: null,
    learnType: "level",
    learnLevel: 35,
    effectKey: "cherry",
    effectMode: "all_each",
    description: "5ターンの間、仲間全員に可愛い女の子に話しかけられる程度の回復",
    battleLog: "/優しく強い雨が降っている...",
  },
  blessing_storm: {
    name: "祝福の嵐",
    type: "heal",
    power: 70,
    cost: 70,
    costType: "mp",
    element: null,
    target: "all_party",
    effect: null,
    learnType: "level",
    learnLevel: 57,
    effectKey: "tornado",
    effectMode: "all_each",
    description: "5ターンの間、仲間全員にめちゃくちゃ暑い日に食べるヴァニラ・アイス並の回復",
    battleLog: "/優しい嵐が巻き起こる...!",
  },
  mana_absorb1: {
    name: "魔力吸収Ⅰ",
    type: "magical",
    power: 5,
    cost: 0,
    costType: null,
    effectKey: "purple_beam",
    effectMode: "single",
    element: null,
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 20,
    description: "敵単体からMPを少し吸収する",
    battleLog: "selfはenemyからnMP吸い取った！",
  },
  mana_absorb2: {
    name: "魔力吸収Ⅱ",
    type: "magical",
    power: 10,
    cost: 0,
    costType: null,
    effectKey: "purple_beam",
    effectMode: "single",
    element: null,
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 40,
    description: "敵単体からMPを吸収する",
    battleLog: "selfはenemyからnMP吸い取った！",
  },
  mana_absorb3: {
    name: "魔力吸収Ⅲ",
    type: "magical",
    power: 15,
    cost: 0,
    costType: null,
    effectKey: "purple_beam",
    effectMode: "single",
    element: null,
    target: "single",
    effect: null,
    learnType: "level",
    learnLevel: 60,
    description: "敵単体からMPをかなり吸収する",
    battleLog: "selfはenemyからnMP吸い取った！",
  },
};

// =============================================
// 連携技（SP消費）
// =============================================
const COMBOS = {
  // 後々追加
};

// =============================================
// 必殺技（UP消費）
// =============================================
const ULTIMATES = {
  // 後々追加
};
